### ISSUE TITLE
Hello, can we add deep reinforcement learning to optimize this system

### ISSUE THREAD

**Issue by DreamerHongzh** [GiorgDiama/SymBChainSim#3]
Hello, can we add deep reinforcement learning to optimize this system

**Comment by GiorgDiama** [comment]
Hello,

Yes, you can achieve this by extracting the relevant state information from the Simulation module (see Metrics.py for an example) to feed to the agent. To apply the agent's decisions, you can use SystemEvents from the Manager module to reconfigure the relevant parameters (you can look at some existing reconfiguration logic in Manager.py). However, this repo contains no built-in RL algorithms, so you must implement and integrate them into the simulation yourself.

I hope that helps! Feel free to open a pull request if you go through with this and want to share.

**Comment by DreamerHongzh** [comment]
Thank you very much

**Comment by GiorgDiama** [comment]
No problem!
